all: perfdata-wall.png perfdata-memory.png perfdata-CPU.png perfdata-read.png perfdata-write.png

# 10 jobs
resource_output-10.summary: harness.sh test1 
	scale=10 ./harness.sh test1/ resource_output-10.summary


perfdata-10.dat : resource_output-10.summary parsejson.py
	scale=10 python parsejson.py < resource_output-10.summary > perfdata-10.dat

#100 jobs
resource_output-100.summary: harness.sh test1 
	scale=100 ./harness.sh test1/ resource_output-100.summary


perfdata-100.dat : resource_output-100.summary parsejson.py
	scale=100 python parsejson.py < resource_output-100.summary > perfdata-100.dat

#1000 jobs 
resource_output-1000.summary: harness.sh test1 
	scale=1000 ./harness.sh test1/ resource_output-1000.summary


perfdata-1000.dat : resource_output-1000.summary parsejson.py
	scale=1000 python parsejson.py < resource_output-1000.summary > perfdata-1000.dat

#10000 jobs 
resource_output-10000.summary: harness.sh test1 
	scale=10000 ./harness.sh test1/ resource_output-10000.summary


perfdata-10000.dat : resource_output-10000.summary parsejson.py
	scale=10000 python parsejson.py < resource_output-10000.summary > perfdata-10000.dat

#100000 jobs 
resource_output-100000.summary: harness.sh test1 
	scale=100000 ./harness.sh test1/ resource_output-100000.summary


perfdata-100000.dat : resource_output-100000.summary parsejson.py
	scale=100000 python parsejson.py < resource_output-100000.summary > perfdata-100000.dat

#50000 jobs 
resource_output-50000.summary: harness.sh test1 
	scale=50000 ./harness.sh test1/ resource_output-50000.summary


perfdata-50000.dat : resource_output-50000.summary parsejson.py
	scale=50000 python parsejson.py < resource_output-50000.summary > perfdata-50000.dat

#20000 jobs 
resource_output-20000.summary: harness.sh test1 
	scale=20000 ./harness.sh test1/ resource_output-20000.summary


perfdata-20000.dat : resource_output-20000.summary parsejson.py
	scale=20000 python parsejson.py < resource_output-20000.summary > perfdata-20000.dat

#30000 jobs 
resource_output-30000.summary: harness.sh test1 
	scale=30000 ./harness.sh test1/ resource_output-30000.summary


perfdata-30000.dat : resource_output-30000.summary parsejson.py
	scale=30000 python parsejson.py < resource_output-30000.summary > perfdata-30000.dat

#40000 jobs 
resource_output-40000.summary: harness.sh test1 
	scale=40000 ./harness.sh test1/ resource_output-40000.summary


perfdata-40000.dat : resource_output-40000.summary parsejson.py
	scale=40000 python parsejson.py < resource_output-40000.summary > perfdata-40000.dat

#60000 jobs 
resource_output-60000.summary: harness.sh test1 
	scale=60000 ./harness.sh test1/ resource_output-60000.summary


perfdata-60000.dat : resource_output-60000.summary parsejson.py
	scale=60000 python parsejson.py < resource_output-60000.summary > perfdata-60000.dat


#70000 jobs 
resource_output-70000.summary: harness.sh test1 
	scale=70000 ./harness.sh test1/ resource_output-70000.summary


perfdata-70000.dat : resource_output-70000.summary parsejson.py
	scale=70000 python parsejson.py < resource_output-70000.summary > perfdata-70000.dat


#80000 jobs 
resource_output-80000.summary: harness.sh test1 
	scale=80000 ./harness.sh test1/ resource_output-80000.summary


perfdata-80000.dat : resource_output-80000.summary parsejson.py
	scale=80000 python parsejson.py < resource_output-80000.summary > perfdata-80000.dat

#90000 jobs 
resource_output-90000.summary: harness.sh test1 
	scale=90000 ./harness.sh test1/ resource_output-90000.summary


perfdata-90000.dat : resource_output-90000.summary parsejson.py
	scale=90000 python parsejson.py < resource_output-90000.summary > perfdata-90000.dat

#15000 jobs 
resource_output-15000.summary: harness.sh test1 
	scale=15000 ./harness.sh test1/ resource_output-15000.summary


perfdata-15000.dat : resource_output-15000.summary parsejson.py
	scale=15000 python parsejson.py < resource_output-15000.summary > perfdata-15000.dat

#25000 jobs 
resource_output-25000.summary: harness.sh test1 
	scale=25000 ./harness.sh test1/ resource_output-25000.summary


perfdata-25000.dat : resource_output-25000.summary parsejson.py
	scale=25000 python parsejson.py < resource_output-25000.summary > perfdata-25000.dat

#35000 jobs 
resource_output-35000.summary: harness.sh test1 
	scale=35000 ./harness.sh test1/ resource_output-35000.summary


perfdata-35000.dat : resource_output-35000.summary parsejson.py
	scale=35000 python parsejson.py < resource_output-35000.summary > perfdata-35000.dat

#45000 jobs 
resource_output-45000.summary: harness.sh test1 
	scale=45000 ./harness.sh test1/ resource_output-45000.summary


perfdata-45000.dat : resource_output-45000.summary parsejson.py
	scale=45000 python parsejson.py < resource_output-45000.summary > perfdata-45000.dat

#55000 jobs 
resource_output-55000.summary: harness.sh test1 
	scale=55000 ./harness.sh test1/ resource_output-55000.summary


perfdata-55000.dat : resource_output-55000.summary parsejson.py
	scale=55000 python parsejson.py < resource_output-55000.summary > perfdata-55000.dat

#65000 jobs 
resource_output-65000.summary: harness.sh test1 
	scale=65000 ./harness.sh test1/ resource_output-65000.summary


perfdata-65000.dat : resource_output-65000.summary parsejson.py
	scale=65000 python parsejson.py < resource_output-65000.summary > perfdata-65000.dat

#75000 jobs 
resource_output-75000.summary: harness.sh test1 
	scale=75000 ./harness.sh test1/ resource_output-75000.summary


perfdata-75000.dat : resource_output-75000.summary parsejson.py
	scale=75000 python parsejson.py < resource_output-75000.summary > perfdata-75000.dat

#85000 jobs 
resource_output-85000.summary: harness.sh test1 
	scale=85000 ./harness.sh test1/ resource_output-85000.summary


perfdata-85000.dat : resource_output-85000.summary parsejson.py
	scale=85000 python parsejson.py < resource_output-85000.summary > perfdata-85000.dat

#95000 jobs 
resource_output-95000.summary: harness.sh test1 
	scale=95000 ./harness.sh test1/ resource_output-95000.summary


perfdata-95000.dat : resource_output-95000.summary parsejson.py
	scale=95000 python parsejson.py < resource_output-95000.summary > perfdata-95000.dat




perfdata.dat : perfdata-10.dat perfdata-100.dat perfdata-1000.dat perfdata-10000.dat perfdata-50000.dat perfdata-100000.dat perfdata-20000.dat perfdata-30000.dat perfdata-40000.dat perfdata-60000.dat perfdata-70000.dat perfdata-80000.dat perfdata-90000.dat perfdata-15000.dat perfdata-25000.dat perfdata-35000.dat perfdata-45000.dat perfdata-55000.dat perfdata-65000.dat perfdata-75000.dat perfdata-85000.dat perfdata-95000.dat
	cat $^ > $@ 

clean: 
	rm -f *.dat *.summary *.png


perfdata-wall.png: perfdata.dat perfdata-wall.gnu
	gnuplot perfdata-wall.gnu

perfdata-memory.png: perfdata.dat perfdata-memory.gnu
	gnuplot perfdata-memory.gnu

perfdata-CPU.png: perfdata.dat perfdata-CPU.gnu
	gnuplot perfdata-CPU.gnu

perfdata-read.png: perfdata.dat perfdata-read.gnu
	gnuplot perfdata-read.gnu

perfdata-write.png: perfdata.dat perfdata-write.gnu
	gnuplot perfdata-write.gnu

